name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ./src/ProdMonitor/ProdMonitor.sln

      - name: Build
        run: dotnet build ./src/ProdMonitor/ProdMonitor.sln --configuration Release --no-restore

      - name: One Integration Test
        run: dotnet test ./src/ProdMonitor/ProdMonitor.sln --filter "GetAssemblyLines_WithExistingAssemblyLines_ReturnsListOfAssemblyLines" --configuration Release --no-restore --no-build

      - name: Test
        run: dotnet test ./src/ProdMonitor/ProdMonitor.sln --configuration Release --no-restore --no-build --logger "console;verbosity=detailed"