name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      

env:
  DOTNET_VERSION: "8.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore 
        run: dotnet restore ./ProdMonitor.ProdMonitor.sln

      - name: Build
        run: dotnet build ./ProdMonitor.ProdMonitor.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./ProdMonitor.ProdMonitor.sln --configuration Release --no-restore --no-build